apiVersion: apps/v1
kind: Deployment

metadata:
  name: abacus-practice-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: abacus-practice

  template:
    metadata:
      labels:
        app: abacus-practice

    spec:
      containers:
        - name: abacus-practice
          image: abacus-practice:1.0
          imagePullPolicy: Never