apiVersion: v1
kind: Service

metadata:
  name: abacus-practice-service

spec:
  selector:
    app: abacus-practice

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

  type: NodePort